
export const OVERVIEW_LOADED = "OVERVIEW_LOADED"
export const OVERVIEW_LOADING = "OVERVIEW_LOADING"
export const USER_LOADED = "USER_LOADED"
export const USER_SIGNED_OUT = "USER_SIGNED_OUT"
export const SETTINGS_CHANGED = "SETTINGS_CHANGED"
