# This file deploys to Firebase Hosting on push to the main branch

name: Deploy to Firebase Hosting on Push to Main
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up environment variables from GitHub secrets
      - name: Set environment variables
        run: |
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_FIREBASE_APP_DOMAIN=${{ secrets.REACT_APP_FIREBASE_APP_DOMAIN }}" >> $GITHUB_ENV
          echo "REACT_APP_GROQ_API_KEY=${{ secrets.REACT_APP_GROQ_API_KEY }}" >> $GITHUB_ENV

      # Install dependencies and build the project
      - run: npm ci --force
      - run: npm run build

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIT_PROMPT }}
          projectId: fit-prompt
          channelId: live
