# This file deploys to Firebase Hosting on push to the main branch

name: Deploy to Firebase Hosting on Push to Main
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci --force && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIT_PROMPT }}
          projectId: fit-prompt
          channelId: live  # Explicitly set to deploy to the live site
